#!/usr/bin/env node
// Post-build: rename Next.js Route Handler output to .json so Cloudflare
// Pages serves them with correct Content-Type, and rebuild _headers with
// rules pinning application/json + CORS for /api/*.
//
// Why: Next 15's `output: 'export'` writes Route Handler responses to
// extensionless files (e.g. out/api/h/<id>). Cloudflare serves those as
// text/plain. Rename → out/api/h/<id>.json so the URL is canonical
// (.../api/h/<id>.json) and the extension drives the served content-type.
//
// Idempotent — safe to re-run on the same out/ tree.

import { readdir, rename, stat, writeFile, readFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { join, resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT = resolve(__dirname, "..", "out");
const API = join(OUT, "api");

if (!existsSync(API)) {
  console.error(`post_build_api: ${API} does not exist — skipping`);
  process.exit(0);
}

let renamed = 0;

async function renameToJson(filepath) {
  if (filepath.endsWith(".json")) return;
  const dest = `${filepath}.json`;
  if (existsSync(dest)) return; // already renamed
  await rename(filepath, dest);
  renamed++;
}

// Walk and rename:
//   out/api/h/<id>            → out/api/h/<id>.json
//   out/api/scoreboard        → out/api/scoreboard.json
//   out/api/hypotheses        → out/api/hypotheses.json
async function walk(dir) {
  const entries = await readdir(dir, { withFileTypes: true });
  for (const entry of entries) {
    const p = join(dir, entry.name);
    if (entry.isDirectory()) {
      await walk(p);
    } else if (entry.isFile()) {
      // Only rename files that don't already have an extension
      if (!entry.name.includes(".")) {
        await renameToJson(p);
      }
    }
  }
}

await walk(API);

// Rebuild _headers — append JSON content-type + permissive CORS for /api/*
// (third-party citation-checkers and dashboards need to fetch from any origin).
const headersPath = join(OUT, "_headers");
let existing = "";
if (existsSync(headersPath)) existing = await readFile(headersPath, "utf8");

const apiBlock = `
# --- Auto-generated by web/scripts/post_build_api.mjs ---
# Pre-rendered JSON API. CORS-open so third-party citation tools, dashboards,
# and newsroom embeds can fetch without proxying. Cache for 10 minutes
# (corpus changes infrequently between deploys; revalidate on demand).
/api/*.json
  Content-Type: application/json; charset=utf-8
  Access-Control-Allow-Origin: *
  Access-Control-Allow-Methods: GET, OPTIONS
  Cache-Control: public, max-age=600, must-revalidate
`;

const marker = "# --- Auto-generated by web/scripts/post_build_api.mjs ---";
let nextHeaders;
if (existing.includes(marker)) {
  // Replace the existing block (idempotent on re-run)
  nextHeaders = existing.replace(
    new RegExp(`\\n?${marker}[\\s\\S]*?(?=\\n# ---|\\n[A-Za-z]|$)`, "m"),
    apiBlock.trimEnd() + "\n"
  );
} else {
  nextHeaders = (existing.trimEnd() + "\n" + apiBlock).trimStart();
}
await writeFile(headersPath, nextHeaders);

// Publish the single-source corpus census as /stats.json for sites, LLMs, and
// journalists that need one consistent counter surface.
const censusSrc = resolve(__dirname, "..", "..", "engine", "public_corpus_census.json");
const statsDest = join(OUT, "stats.json");
if (existsSync(censusSrc)) {
  const census = await readFile(censusSrc, "utf8");
  await writeFile(statsDest, census);
  console.log(`post_build_api: wrote ${statsDest}`);
} else {
  console.warn(`post_build_api: census missing at ${censusSrc} — stats.json not written`);
}

// Ensure llms.txt / feed.xml made it into out/ (Next copies public/ automatically;
// log for operators when they are present).
for (const name of ["llms.txt", "feed.xml", "robots.txt", "sitemap.xml"]) {
  const p = join(OUT, name);
  console.log(
    existsSync(p)
      ? `post_build_api: present ${name}`
      : `post_build_api: missing ${name}`
  );
}

console.log(`post_build_api: renamed ${renamed} files to .json`);
console.log(`post_build_api: updated ${headersPath}`);
