#!/usr/bin/env python3
from __future__ import annotations

import hashlib
import json
from datetime import datetime, timezone
from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parents[3]
HID = "friedman_schwartz_great_depression_monetary_cause"
OUT = ROOT / "engine" / "runs" / HID


def latest(pub: str, series: str) -> Path:
    files = sorted((ROOT / "data" / "vintages" / pub).glob(f"{series}@*.parquet"))
    if not files:
        raise FileNotFoundError(f"missing {pub}:{series}")
    return files[-1]


def sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def pct(a: float, b: float) -> float:
    return 100.0 * (b / a - 1.0)


def log_ppt(a: float, b: float) -> float:
    return 100.0 * (np.log(b) - np.log(a))


def main() -> int:
    OUT.mkdir(parents=True, exist_ok=True)
    path = latest("jst", "real_gdp")
    df = pd.read_parquet(path)
    usa = df[df["country_iso3"].eq("USA")].set_index("year")
    a, b = usa.loc[1929], usa.loc[1933]
    metrics = {
        "money_pct_change_1929_1933": pct(a["money"], b["money"]),
        "money_log_ppt_change_1929_1933": log_ppt(a["money"], b["money"]),
        "nominal_gdp_pct_change_1929_1933": pct(a["gdp"], b["gdp"]),
        "real_gdp_pct_change_1929_1933": pct(a["rgdpmad"], b["rgdpmad"]),
        "cpi_pct_change_1929_1933": pct(a["cpi"], b["cpi"]),
        "unemployment_pp_change_1929_1933": float(b["unemp"] - a["unemp"]),
    }
    if (
        metrics["money_log_ppt_change_1929_1933"] <= -25
        and metrics["nominal_gdp_pct_change_1929_1933"] <= -25
        and metrics["real_gdp_pct_change_1929_1933"] <= -20
    ):
        verdict, reason = "SUPPORTED", "JST money, nominal GDP, and real GDP all clear the 1929-1933 contraction gates"
    elif (
        metrics["money_log_ppt_change_1929_1933"] > -10
        or metrics["nominal_gdp_pct_change_1929_1933"] > -10
    ):
        verdict, reason = "REFUTED", "money or nominal GDP contraction is too small for the registered monetary-collapse gate"
    else:
        verdict, reason = "PARTIAL", "direction matches but at least one contraction gate is below threshold"

    diag = {
        "verdict": f"{verdict} - {reason}",
        "verdict_label": verdict,
        "verdict_reason": reason,
        "hypothesis_id": HID,
        "template": "descriptive_exact_jst",
        "metrics": metrics,
        "data_status": {
            "variables_loaded": [
                {"source": "jst:real_gdp", "vintage_file": str(path.relative_to(ROOT)), "sha256": sha256(path)}
            ],
            "variables_missing": [],
        },
        "run_utc": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "runner": "engine/runs/friedman_schwartz_great_depression_monetary_cause/replication.py",
    }
    (OUT / "diagnostics.json").write_text(json.dumps(diag, indent=2))
    (OUT / "manifest.yaml").write_text(
        f"hypothesis_id: {HID}\n"
        "sources:\n"
        f"  jst_real_gdp: {path.relative_to(ROOT)}\n"
        f"run_utc: {diag['run_utc']}\n"
    )
    rows = "\n".join(f"- **{k}:** {v:.3f}" for k, v in metrics.items())
    (OUT / "result_card.md").write_text(
        f"# Result card - {HID}\n\n"
        f"**Verdict:** {verdict} - {reason}\n\n"
        "## Exact JST Great Depression Gates\n"
        f"{rows}\n\n"
        "## Interpretation\n"
        "The local JST macrohistory panel shows the money stock falling with the output and price-level collapse between 1929 and 1933. "
        "This validates the monetary-contraction timing/magnitude gate, while leaving causality and banking-panic mechanisms as interpretive caveats.\n\n"
        f"_Generated by `engine/runs/{HID}/replication.py` at {diag['run_utc']}_\n"
    )
    print(json.dumps({"hypothesis_id": HID, "verdict": verdict, "reason": reason}, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
