#!/usr/bin/env python3
from __future__ import annotations

import hashlib
import json
from datetime import datetime, timezone
from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parents[3]
HID = "macron_labour_tax_employment_distribution"
OUT = ROOT / "engine" / "runs" / HID


def latest(pub: str, pattern: str) -> Path:
    files = sorted((ROOT / "data" / "vintages" / pub).glob(pattern))
    if not files:
        raise FileNotFoundError(f"missing {pub}:{pattern}")
    return files[-1]


def sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def main() -> int:
    OUT.mkdir(parents=True, exist_ok=True)
    u_path = latest("world_bank_wdi", "SL.UEM.TOTL.ZS@*.parquet")
    u = pd.read_parquet(u_path)
    fra = u[u["country_iso3"].eq("FRA")][["year", "value"]].dropna().copy()
    pre = fra[(fra["year"] >= 2010) & (fra["year"] < 2017)]
    post = fra[(fra["year"] >= 2017) & (fra["year"] <= 2019)]
    x = np.vstack([np.ones(len(pre)), pre["year"].to_numpy(dtype=float)]).T
    beta = np.linalg.lstsq(x, pre["value"].to_numpy(dtype=float), rcond=None)[0]
    trend = np.vstack([np.ones(len(post)), post["year"].to_numpy(dtype=float)]).T @ beta
    gaps = post["value"].to_numpy(dtype=float) - trend

    g_path = latest("oecd", "*IDD*DF_IDD*.parquet")
    g = pd.read_parquet(g_path)
    gini = g[
        g["REF_AREA"].eq("FRA")
        & g["MEASURE"].eq("INC_DISP_GINI")
        & g["AGE"].eq("_T")
        & g["METHODOLOGY"].eq("METH2012")
    ][["period", "value"]].dropna()
    gini = gini.groupby("period", as_index=False)["value"].mean()
    g2016 = float(gini[gini["period"].eq(2016)]["value"].iloc[0])
    g2019 = float(gini[gini["period"].eq(2019)]["value"].iloc[0])
    gini_delta = g2019 - g2016
    employment_leg = float(gaps[-1]) <= -0.5
    distribution_leg = gini_delta >= 0.005
    if employment_leg and distribution_leg:
        verdict, reason = "SUPPORTED", "unemployment and distributional-cost legs both clear"
    elif not employment_leg:
        verdict, reason = "REFUTED", "unemployment does not fall at least 0.5pp below pre-trend by 2019"
    else:
        verdict, reason = "PARTIAL", "employment leg clears but disposable-income Gini does not rise by 0.005"
    run_utc = datetime.now(timezone.utc).isoformat(timespec="seconds")
    est = {
        "pretrend_window": [2010, 2016],
        "post_window": [2017, 2019],
        "post_unemployment_gaps_pp": [
            {"year": int(year), "actual": float(actual), "trend": float(t), "gap_pp": float(g)}
            for year, actual, t, g in zip(post["year"], post["value"], trend, gaps)
        ],
        "end_2019_unemployment_gap_pp": float(gaps[-1]),
        "mean_2017_2019_unemployment_gap_pp": float(np.mean(gaps)),
        "disposable_gini_2016": g2016,
        "disposable_gini_2019": g2019,
        "disposable_gini_delta": gini_delta,
    }
    diag = {
        "verdict": f"{verdict} - {reason}",
        "verdict_label": verdict,
        "verdict_reason": reason,
        "hypothesis_id": HID,
        "template": "national_event_study_exact",
        "estimate": est,
        "data_status": {
            "variables_loaded": [
                {"source": "world_bank_wdi:SL.UEM.TOTL.ZS", "vintage_file": str(u_path.relative_to(ROOT)), "sha256": sha256(u_path)},
                {"source": "oecd:DSD_IDD@DF_IDD", "vintage_file": str(g_path.relative_to(ROOT)), "sha256": sha256(g_path)},
            ],
            "variables_missing": ["regional employment panel", "tax-reform treatment intensity"],
        },
        "run_utc": run_utc,
        "runner": f"engine/runs/{HID}/replication.py",
    }
    (OUT / "diagnostics.json").write_text(json.dumps(diag, indent=2))
    (OUT / "manifest.yaml").write_text(
        f"hypothesis_id: {HID}\n"
        "sources:\n"
        f"  france_unemployment: {u_path.relative_to(ROOT)}\n"
        f"  france_disposable_gini: {g_path.relative_to(ROOT)}\n"
        f"run_utc: {run_utc}\n"
    )
    (OUT / "result_card.md").write_text(
        f"# Result card - {HID}\n\n"
        f"**Verdict:** {verdict} - {reason}\n\n"
        "## National Event Benchmark\n"
        f"- 2019 unemployment gap vs 2010-2016 pre-trend: **{gaps[-1]:.2f} pp**.\n"
        f"- Mean 2017-2019 unemployment gap: **{np.mean(gaps):.2f} pp**.\n"
        f"- Disposable-income Gini change, 2016-2019: **{gini_delta:.3f}**.\n\n"
        "This benchmark validates the employment-improvement leg but not the registered distributional-cost leg.\n\n"
        f"_Generated by `engine/runs/{HID}/replication.py` at {run_utc}_\n"
    )
    print(json.dumps({"hypothesis_id": HID, "verdict": verdict, "reason": reason}, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
