#!/usr/bin/env python3
"""Regenerate this OWID energy wave run artifact.

This run is generated by scripts/generate_owid_energy_wave.py so the replication
logic stays shared across the small OWID wave while artifacts remain per-run.
"""
from pathlib import Path
import runpy

root = Path(__file__).resolve().parents[3]
runpy.run_path(str(root / "scripts" / "generate_owid_energy_wave.py"), run_name="__main__")
